name: processdesignjobs.com
favicon: null
layout_spectrum: 0.5734170326031744
typography_spectrum: 0.07617127802222967
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.769743358483538
  lightness: 0.2904671842698008
  saturation: 0.9054732725489885
  rhythmicContrast: 0.7672190216835588
purpose: []
